FROM node:20-alpine3.20 AS builder

WORKDIR /app

COPY . .

# ENV
# ARG API_BACKEND=
# ARG OAUTH2_ISSUER=
# ARG OAUTH2_CLIENT_ID=
# ARG OAUTH2_REDIRECT_URI=
# ARG XAPPID=
# ARG APPLE_APP_ID=

ENV API_BACKEND=http://gsbmycarduat.gsb.or.th
ENV OAUTH2_ISSUER=https://mfapwldev.gsb.or.th
ENV OAUTH2_CLIENT_ID=0oa1uk5axxcJJh8mB1d8
ENV OAUTH2_REDIRECT_URI=https://gsbmycarduat.gsb.or.th/cms/auth/callback
ENV XAPPID=9df6dceb
ENV APPLE_APP_ID=L679254MM2.com.ubakong.gsb.gsbmcc-uat

# RUN echo $API_BACKEND
# RUN echo $OAUTH2_ISSUER
# RUN echo $OAUTH2_CLIENT_ID
# RUN echo $OAUTH2_REDIRECT_URI
# RUN echo $XAPPID
# RUN echo $APPLE_APP_ID

# Install gettext
RUN apk update
RUN apk add --no-cache gettext=0.22.5-r0

RUN chmod +x docker-entrypoint.sh
RUN ./docker-entrypoint.sh

RUN yarn install --unsafe-perm
RUN yarn build-prod

FROM nginx:1.26.3-alpine3.20

# Install gettext
RUN apk update
RUN apk add --no-cache gettext=0.22.5-r0

RUN addgroup -S nonroot \
    && adduser -S nonroot -G nonroot

COPY --from=builder /app/nginx.default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist/* /etc/nginx/html
COPY --from=builder /app/.well-known/* /etc/nginx/html/.well-known/

RUN chown -R nonroot:nonroot /etc/nginx/
RUN chown -R nonroot:nonroot /var/cache/nginx/
RUN chown -R nonroot:nonroot /var/run/

# EXPOSE 80
EXPOSE 8080

USER nonroot

CMD ["nginx", "-g", "daemon off;"]